name: generate-index
run-name: Generating touhou.events archive index
on: [push]
jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run Generate Index
      #print current directory
        run: python -c "import os; print(os.getcwd())"
        env:
          WORKSPACE: ${{ github.workspace }}

      - uses: actions/upload-artifact@v2
        with:
          name: index